server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: self-test
              uri: http://localhost:${server.port:8765}
              predicates:
                - Path=/proxy/**
              filters:
                - StripPrefix=1
            - id: core-test
              uri: ${CORE_BASE_URL}
              predicates:
                - Path=/hello
              filters:
                - TokenRelay=

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: ${DEV_CLIENT_SECRET}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_SCHEME}://keycloak:${KEYCLOAK_PORT}/realms/DACS

logging:
  pattern:
    level: "%5p [%X{requestId:-}]"